# .gitlab-ci.yml – version simplifiée & sûre
image: node:20

stages: [build, deploy]

cache:
  paths:
    - node_modules/

variables:
  # clés publiques uniquement
  VITE_SUPABASE_URL: $VITE_SUPABASE_URL
  VITE_SUPABASE_ANON_KEY: $VITE_SUPABASE_ANON_KEY
  VITE_BASE_PATH: /

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script: |
    mkdir -p public
    cp -a dist/. public/
  artifacts:
    paths:
      - public
  only:
    - main
